# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0014_auto_20151211_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
