# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:36
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160226_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=versatileimagefield.fields.VersatileImageField(upload_to='imagenes/', verbose_name='Image'),
        ),
    ]
