# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_casa_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservacion',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
    ]
